# Generated by Django 4.2.3 on 2023-07-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.ImageField(max_length=11, unique=True, upload_to=''),
        ),
    ]
